#!/usr/bin/python3
import socket
import sys
import argparse
import re
from time import sleep

socket_path = "/opt/cellframe-node/var/run/node_cli" # Local socket for connections
parser = argparse.ArgumentParser()
parser.add_argument("--ip", type=str, required=False, help="Host IP (ext. address)")
parser.add_argument("--port", type=int, required=False, help="Socat forwarded port")
args = parser.parse_args()

info =  '''
******************************** CELLFRAME NODE CLI ********************************
****       THIS CLIENT CAN BE USED AS A SUBSTITUTE FOR CELLFRAME-NODE-CLI       ****
****                      TYPE QUIT TO EXIT THIS CLIENT                         ****
************************************************************************************'''

print(info)

while True:
    connected = False
    if args.ip and args.port:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        while not connected:
            try:
                s.connect((args.ip, args.port))
                connected = True
            except:
                print("Couldn't connect to socket, is it forwarded with socat? Trying again... (Exit with CTRL+C)")
                sleep(5)
    else:
        s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        while not connected:
            try:
                s.connect(socket_path)
                connected = True
            except:
                print("Couldn't connect to socket! Node is running? Trying again... (Exit with CTRL+C)")
                sleep(5)

    command = input("> ")
    if command == "quit": # We need to use quit for exiting the client because exit is actually sent to node...
        print("Exiting...")
        s.shutdown(socket.SHUT_RDWR)
        s.close()
        sys.exit()
    length = str(len(command))
    command = re.sub('\\s+', " ", command) # Multiple spaces are one space, yes?
    command = command.replace(" ", "\r\n")
    post = "POST /connect HTTP/1.1\r\nHost: localhost\r\nContent-Type: text/text\r\nContent-Length: " + length + "\r\n\r\n" + command + "\r\n\r\n"
    post = bytes(post,"utf-8")
    s.sendall(post)
    reply = s.recv(4096)
    reply = reply.decode("utf-8")
    reply = reply.split("\n")
    reply = list(filter(None, reply))
    reply = reply[4:]
    reply.sort() # Sort the reply, easier to navigate at least when using "help"
    for replies in reply:
        print(replies)
    s.shutdown(socket.SHUT_RDWR)
    s.close()